# Setup
title:               Solomic
email:               blog.solomic@gmail.com
tagline:             'for education, business, investment and technology'
description:         'fresh ideas for a challenging world'
url:                 http://blog.solomic.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Solomic Blog
  url:               https://twitter.com/solomic
  email:             blog.solomic@gmail.com
twitter_username:    solomic2
github_username:     blog-solomic

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-34SPSTFGMH